# Generated by Django 4.2.1 on 2023-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
